### ISSUE TITLE
Blue Line when cutting

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#171]
When cutting the freehand polygon the blue line will stay moving with your cursor when you go to click the ingest button. If you wanted to cut another area on the same image or move to another image you will need to turn off cutting. It would be cleaner if the line turned off after the cut

**Comment by melbsurfer** [comment]
Looked into this issue, and I think the problem has been fixed in the latest baseline.  The freehand poly tool will stay active after creating a poly feature, and the cursor will retain the blue dot indicating that the tool is active.  However, last week I added a clear poly feature button that will remove the cut area.  This way a user can generate a cut area, ingest from one image, and then reuse to the cut area on another image (assuming the next preview image is over the same area).  

I believe this new behavior solves this issue.  Closing , and can re-open if this is not the desired workflow.
