### ISSUE TITLE
Implement Jasmine client-side testing environment

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#72]
Mocha/Chai or Jasmine - client-side testing

!story G17.6
!component test

**Comment by melbsurfer** [comment]
Stared working with Jasmine.js for client-side testing.  Looked into plugin's, but I am not sure this is the way to go right now.  Been talking to Scottie to find out the best way to get this working in a Grails project

**Comment by melbsurfer** [comment]
Jasmine testing environment has been added to the project in the web-app static file directory.  I also added the $inject.js library so that we could test inside of our modules.  I was having a problem writing tests against our existing code because we are following the module pattern, and putting everything in IIIFE's (Immediately-Invoked Function Expressions).  $ingest.js fixes this, and allows us to drill into the modules and test individual components.

**Comment by melbsurfer** [comment]
Added three new spec's last night that test the $ajax request being sent to the create, update, and delete methods.  I think we should move this task to 'Done', with the understanding that new client-side development should be utilizing this new testing environment.
